import { KPI, KPIVersion } from "./types";
import { Activity, DollarSign, TrendingDown } from "lucide-react";

export const kpiCategories = {
  Operational: [
    "CUF",
    "Grid Availability (GA)",
    "Plant Availability (PA)",
    "Plant Available Factor (PAF)",
    "Transmission Line Loss (TLL)",
    "Reactive Power Withdrawal",
    "Curtailment Loss",
    "Lost Production Index (LPI)",
  ],
  Commercial: [
    "Revenue Realization",
    "Revenue Shortfall",
    "O&M Deviation",
    "Liquidated Damages (LD)",
    "ROI",
    "Payback Period",
  ],
  "AI/Predictive": [
    "Degradation Ratio (PDR)",
    "Forecasted Generation",
    "Curtailment Pattern Analysis",
  ],
};

export const kpiData: KPI[] = [
  // Operational
  {
    id: "cuf",
    name: "CUF",
    category: "Operational",
    currentValue: 22.4,
    targetValue: 23.0,
    unit: "%",
    complianceStatus: "Warning",
    momChange: -2.6,
    trend: [21.8, 22.1, 23.2, 22.8, 22.3, 22.6, 22.4],
    description: "Capacity Utilization Factor based on actual generation vs installed capacity.",
    ppaType: "PPA-Solar-2018",
    effectiveVersion: "v1.2",
    impactedPlants: 12,
    revenueImpact: -450000,
    ldRisk: 125000,
    benchmarkSource: "Annexure C, Clause 4.2",
    history: [
      { month: "Jan", value: 22.6, target: 23.0 },
      { month: "Feb", value: 22.4, target: 23.0 },
      { month: "Mar", value: 23.1, target: 23.0 },
      { month: "Apr", value: 22.9, target: 23.0 },
      { month: "May", value: 22.2, target: 23.0 },
      { month: "Jun", value: 21.8, target: 23.0 },
    ],
    plantBreakdown: [
      { plant: "Sakri Solar Park", cluster: "Dhule", vendor: "SolarCo India", value: 21.5, status: "Non-Compliant" },
      { plant: "Sangli Solar Farm", cluster: "Dhule", vendor: "SunPower Tech", value: 22.8, status: "Warning" },
      { plant: "Osmanabad Solar Plant", cluster: "Osmanabad", vendor: "Green Energy Ltd", value: 23.5, status: "Compliant" },
    ],
    waterfallData: [
      { step: "Budgeted", value: 24.0, type: "total" },
      { step: "Irradiance Adj", value: -0.5, type: "decrease" },
      { step: "Temp Adj", value: -0.2, type: "decrease" },
      { step: "Expected", value: 23.3, type: "total" },
      { step: "Grid Outage", value: -0.4, type: "decrease" },
      { step: "Plant Faults", value: -0.5, type: "decrease" },
      { step: "Actual", value: 22.4, type: "total" },
    ],
    versions: [
      {
        version: "v1.2",
        effectiveDate: "2024-01-01",
        snapshot: "CUF = (Gen / (Cap * Hours)) * 100",
        approvedBy: "John Doe",
        status: "Active",
        revenueImpactChange: 0,
        ldExposureChange: 0,
        complianceChange: 0,
      },
      {
        version: "v1.1",
        effectiveDate: "2023-06-01",
        snapshot: "CUF = (Gen / (Cap * Hours)) * 100",
        approvedBy: "Jane Smith",
        status: "Archived",
        revenueImpactChange: -50000,
        ldExposureChange: 10000,
        complianceChange: -2.5,
      },
    ],
  },
  {
    id: "ga",
    name: "Grid Availability (GA)",
    category: "Operational",
    currentValue: 98.5,
    targetValue: 98.0,
    unit: "%",
    complianceStatus: "Compliant",
    momChange: 0.5,
    trend: [97.2, 97.8, 98.5, 98.0, 97.5, 98.2, 98.5],
    description: "Percentage of time the grid was available for power injection.",
    ppaType: "PPA-Standard-2019",
    effectiveVersion: "v2.0",
    impactedPlants: 0,
    revenueImpact: 0,
    ldRisk: 0,
    benchmarkSource: "Clause 5.1",
    history: [
      { month: "Jan", value: 97.8, target: 98.0 },
      { month: "Feb", value: 98.2, target: 98.0 },
      { month: "Mar", value: 98.0, target: 98.0 },
      { month: "Apr", value: 97.5, target: 98.0 },
      { month: "May", value: 98.5, target: 98.0 },
      { month: "Jun", value: 98.5, target: 98.0 },
    ],
    plantBreakdown: [
      { plant: "Sakri Solar Park", cluster: "Dhule", vendor: "SolarCo India", value: 98.2, status: "Compliant" },
      { plant: "Sangli Solar Farm", cluster: "Sangli", vendor: "SunPower Tech", value: 98.8, status: "Compliant" },
      { plant: "Osmanabad Solar Plant", cluster: "Osmanabad", vendor: "Green Energy Ltd", value: 98.5, status: "Compliant" },
      { plant: "Latur Solar Station", cluster: "Latur", vendor: "TechSolar Pvt", value: 97.9, status: "Warning" },
    ],
    waterfallData: [
      { step: "Total Hours", value: 100.0, type: "total" },
      { step: "Planned Outage", value: -0.8, type: "decrease" },
      { step: "Unplanned Outage", value: -0.5, type: "decrease" },
      { step: "Force Majeure", value: -0.2, type: "decrease" },
      { step: "Actual GA", value: 98.5, type: "total" },
    ],
    versions: [
      {
        version: "v2.0",
        effectiveDate: "2024-01-01",
        snapshot: "GA = (Available Hours / Total Hours) * 100",
        approvedBy: "Rajesh Kumar",
        status: "Active",
        revenueImpactChange: 0,
        ldExposureChange: 0,
        complianceChange: 0,
      },
    ],
  },
  {
    id: "pa",
    name: "Plant Availability (PA)",
    category: "Operational",
    currentValue: 97.8,
    targetValue: 95.0,
    unit: "%",
    complianceStatus: "Compliant",
    momChange: 2.9,
    trend: [96.5, 96.8, 97.2, 97.0, 96.7, 97.5, 97.8],
    description: "Time the plant was available to generate power.",
    ppaType: "PPA-Standard-2019",
    effectiveVersion: "v1.1",
    impactedPlants: 2,
    revenueImpact: 150000,
    ldRisk: 0,
    benchmarkSource: "Clause 5.2",
    history: [
      { month: "Jan", value: 96.5, target: 95.0 },
      { month: "Feb", value: 96.8, target: 95.0 },
      { month: "Mar", value: 97.2, target: 95.0 },
      { month: "Apr", value: 97.0, target: 95.0 },
      { month: "May", value: 96.7, target: 95.0 },
      { month: "Jun", value: 97.8, target: 95.0 },
    ],
    plantBreakdown: [
      { plant: "Sakri Solar Park", cluster: "Dhule", vendor: "SolarCo India", value: 96.5, status: "Compliant" },
      { plant: "Sangli Solar Farm", cluster: "Sangli", vendor: "SunPower Tech", value: 98.2, status: "Compliant" },
      { plant: "Osmanabad Solar Plant", cluster: "Osmanabad", vendor: "Green Energy Ltd", value: 97.8, status: "Compliant" },
      { plant: "Latur Solar Station", cluster: "Ahmednagar", vendor: "Green Energy Ltd", value: 94.2, status: "Warning" },
    ],
    waterfallData: [
      { step: "Total Hours", value: 100.0, type: "total" },
      { step: "Scheduled Maintenance", value: -1.2, type: "decrease" },
      { step: "Equipment Failure", value: -0.8, type: "decrease" },
      { step: "Other Downtime", value: -0.2, type: "decrease" },
      { step: "Actual PA", value: 97.8, type: "total" },
    ],
    versions: [
      {
        version: "v1.1",
        effectiveDate: "2023-07-01",
        snapshot: "PA = (Available Time / Contract Time) * 100",
        approvedBy: "Priya Sharma",
        status: "Active",
        revenueImpactChange: 0,
        ldExposureChange: 0,
        complianceChange: 0,
      },
    ],
  },
  {
    id: "paf",
    name: "Plant Available Factor (PAF)",
    category: "Operational",
    currentValue: 94.2,
    targetValue: 93.0,
    unit: "%",
    complianceStatus: "Compliant",
    momChange: 1.3,
    trend: [92.8, 93.1, 93.5, 93.8, 93.6, 94.0, 94.2],
    description: "Combined availability metric considering both technical and grid constraints.",
    ppaType: "PPA-Solar-2018",
    effectiveVersion: "v1.0",
    impactedPlants: 0,
    revenueImpact: 85000,
    ldRisk: 0,
    benchmarkSource: "Annexure D, Clause 3.1",
    history: [
      { month: "Jan", value: 92.8, target: 93.0 },
      { month: "Feb", value: 93.1, target: 93.0 },
      { month: "Mar", value: 93.5, target: 93.0 },
      { month: "Apr", value: 93.8, target: 93.0 },
      { month: "May", value: 93.6, target: 93.0 },
      { month: "Jun", value: 94.2, target: 93.0 },
    ],
    plantBreakdown: [
      { plant: "Sakri Solar Park", cluster: "Dhule", vendor: "SolarCo India", value: 93.8, status: "Compliant" },
      { plant: "Sangli Solar Farm", cluster: "Sangli", vendor: "SunPower Tech", value: 94.5, status: "Compliant" },
      { plant: "Osmanabad Solar Plant", cluster: "Osmanabad", vendor: "Green Energy Ltd", value: 94.2, status: "Compliant" },
      { plant: "Latur Solar Station", cluster: "Latur", vendor: "TechSolar Pvt", value: 92.5, status: "Warning" },
    ],
    waterfallData: [
      { step: "Plant Availability", value: 97.8, type: "total" },
      { step: "Grid Curtailment", value: -2.1, type: "decrease" },
      { step: "Transmission Loss", value: -1.2, type: "decrease" },
      { step: "Reactive Power Adj", value: -0.3, type: "decrease" },
      { step: "Actual PAF", value: 94.2, type: "total" },
    ],
    versions: [
      {
        version: "v1.0",
        effectiveDate: "2024-01-01",
        snapshot: "PAF = PA * GA * (1 - TLL/100)",
        approvedBy: "Amit Singh",
        status: "Active",
        revenueImpactChange: 0,
        ldExposureChange: 0,
        complianceChange: 0,
      },
    ],
  },
  {
    id: "tll",
    name: "Transmission Line Loss (TLL)",
    category: "Operational",
    currentValue: 3.2,
    targetValue: 3.5,
    unit: "%",
    complianceStatus: "Compliant",
    momChange: -0.3,
    trend: [3.5, 3.4, 3.6, 3.3, 3.4, 3.1, 3.2],
    description: "Percentage of energy lost during transmission from plant to grid interconnection point.",
    ppaType: "PPA-Standard-2019",
    effectiveVersion: "v1.2",
    impactedPlants: 8,
    revenueImpact: 120000,
    ldRisk: 0,
    benchmarkSource: "Technical Schedule, Clause 7.3",
    history: [
      { month: "Jan", value: 3.5, target: 3.5 },
      { month: "Feb", value: 3.4, target: 3.5 },
      { month: "Mar", value: 3.6, target: 3.5 },
      { month: "Apr", value: 3.3, target: 3.5 },
      { month: "May", value: 3.4, target: 3.5 },
      { month: "Jun", value: 3.2, target: 3.5 },
    ],
    plantBreakdown: [
      { plant: "Sakri Solar Park", cluster: "Dhule", vendor: "SolarCo India", value: 2.8, status: "Compliant" },
      { plant: "Sangli Solar Farm", cluster: "Sangli", vendor: "SunPower Tech", value: 3.1, status: "Compliant" },
      { plant: "Osmanabad Solar Plant", cluster: "Osmanabad", vendor: "Green Energy Ltd", value: 3.2, status: "Compliant" },
      { plant: "Beed Solar Park", cluster: "Beed", vendor: "Mega Solar Inc", value: 4.2, status: "Warning" },
    ],
    waterfallData: [
      { step: "Generation at Busbar", value: 100.0, type: "total" },
      { step: "Transformer Loss", value: -1.2, type: "decrease" },
      { step: "Line Resistance", value: -1.5, type: "decrease" },
      { step: "Corona Loss", value: -0.3, type: "decrease" },
      { step: "Other Losses", value: -0.2, type: "decrease" },
      { step: "Net Injection", value: 96.8, type: "total" },
    ],
    versions: [
      {
        version: "v1.2",
        effectiveDate: "2024-03-01",
        snapshot: "TLL = ((Gen - Injected) / Gen) * 100",
        approvedBy: "Vikram Reddy",
        status: "Active",
        revenueImpactChange: 0,
        ldExposureChange: 0,
        complianceChange: 0,
      },
    ],
  },
  {
    id: "rpw",
    name: "Reactive Power Withdrawal",
    category: "Operational",
    currentValue: 1.8,
    targetValue: 2.0,
    unit: "MVAr",
    complianceStatus: "Compliant",
    momChange: -10.0,
    trend: [2.1, 2.0, 1.9, 1.9, 2.0, 1.9, 1.8],
    description: "Average reactive power drawn from the grid for plant operations.",
    ppaType: "PPA-Standard-2019",
    effectiveVersion: "v1.0",
    impactedPlants: 4,
    revenueImpact: 45000,
    ldRisk: 0,
    benchmarkSource: "Grid Code, Section 8.2",
    history: [
      { month: "Jan", value: 2.1, target: 2.0 },
      { month: "Feb", value: 2.0, target: 2.0 },
      { month: "Mar", value: 1.9, target: 2.0 },
      { month: "Apr", value: 1.9, target: 2.0 },
      { month: "May", value: 2.0, target: 2.0 },
      { month: "Jun", value: 1.8, target: 2.0 },
    ],
    plantBreakdown: [
      { plant: "Sakri Solar Park", cluster: "Dhule", vendor: "SolarCo India", value: 1.7, status: "Compliant" },
      { plant: "Sangli Solar Farm", cluster: "Sangli", vendor: "SunPower Tech", value: 1.8, status: "Compliant" },
      { plant: "Osmanabad Solar Plant", cluster: "Osmanabad", vendor: "Green Energy Ltd", value: 1.9, status: "Compliant" },
      { plant: "Latur Solar Station", cluster: "Ahmednagar", vendor: "Green Energy Ltd", value: 2.2, status: "Warning" },
    ],
    waterfallData: [
      { step: "Baseline Requirement", value: 2.5, type: "total" },
      { step: "Power Factor Correction", value: -0.4, type: "decrease" },
      { step: "Capacitor Bank", value: -0.2, type: "decrease" },
      { step: "Grid Support", value: -0.1, type: "decrease" },
      { step: "Net Withdrawal", value: 1.8, type: "total" },
    ],
    versions: [
      {
        version: "v1.0",
        effectiveDate: "2023-01-01",
        snapshot: "RPW = Avg(Q_withdrawn) over billing period",
        approvedBy: "Suresh Iyer",
        status: "Active",
        revenueImpactChange: 0,
        ldExposureChange: 0,
        complianceChange: 0,
      },
    ],
  },
  {
    id: "curtailment",
    name: "Curtailment Loss",
    category: "Operational",
    currentValue: 4.2,
    targetValue: 3.0,
    unit: "%",
    complianceStatus: "Non-Compliant",
    momChange: 40.0,
    trend: [2.8, 3.1, 3.5, 3.2, 3.8, 4.0, 4.2],
    description: "Generation curtailed due to grid constraints or dispatch instructions.",
    ppaType: "PPA-Solar-2018",
    effectiveVersion: "v2.1",
    impactedPlants: 15,
    revenueImpact: -680000,
    ldRisk: 180000,
    benchmarkSource: "Dispatch Protocol, Clause 12.1",
    history: [
      { month: "Jan", value: 2.8, target: 3.0 },
      { month: "Feb", value: 3.1, target: 3.0 },
      { month: "Mar", value: 3.5, target: 3.0 },
      { month: "Apr", value: 3.2, target: 3.0 },
      { month: "May", value: 3.8, target: 3.0 },
      { month: "Jun", value: 4.2, target: 3.0 },
    ],
    plantBreakdown: [
      { plant: "Sakri Solar Park", cluster: "Dhule", vendor: "SolarCo India", value: 5.2, status: "Non-Compliant" },
      { plant: "Sangli Solar Farm", cluster: "Sangli", vendor: "SunPower Tech", value: 4.8, status: "Non-Compliant" },
      { plant: "Osmanabad Solar Plant", cluster: "Osmanabad", vendor: "Green Energy Ltd", value: 3.5, status: "Warning" },
      { plant: "Devdaithan Solar Plant", cluster: "Ahmednagar", vendor: "Mega Solar Inc", value: 2.8, status: "Compliant" },
    ],
    waterfallData: [
      { step: "Potential Generation", value: 100.0, type: "total" },
      { step: "Grid Congestion", value: -2.1, type: "decrease" },
      { step: "Frequency Regulation", value: -1.2, type: "decrease" },
      { step: "RLDC Instructions", value: -0.9, type: "decrease" },
      { step: "Actual Generation", value: 95.8, type: "total" },
    ],
    versions: [
      {
        version: "v2.1",
        effectiveDate: "2024-06-01",
        snapshot: "Curtailment = ((Potential - Actual) / Potential) * 100",
        approvedBy: "Neha Gupta",
        status: "Active",
        revenueImpactChange: 0,
        ldExposureChange: 0,
        complianceChange: 0,
      },
      {
        version: "v2.0",
        effectiveDate: "2023-12-01",
        snapshot: "Curtailment = ((Potential - Actual) / Potential) * 100",
        approvedBy: "Rakesh Verma",
        status: "Archived",
        revenueImpactChange: -120000,
        ldExposureChange: 40000,
        complianceChange: -1.2,
      },
    ],
  },
  {
    id: "lpi",
    name: "Lost Production Index (LPI)",
    category: "Operational",
    currentValue: 6.8,
    targetValue: 5.0,
    unit: "%",
    complianceStatus: "Warning",
    momChange: 36.0,
    trend: [4.5, 4.8, 5.2, 5.5, 6.0, 6.5, 6.8],
    description: "Total production loss index combining all operational losses.",
    ppaType: "PPA-Solar-2018",
    effectiveVersion: "v1.5",
    impactedPlants: 18,
    revenueImpact: -820000,
    ldRisk: 250000,
    benchmarkSource: "Performance Benchmark, Annexure E",
    history: [
      { month: "Jan", value: 4.5, target: 5.0 },
      { month: "Feb", value: 4.8, target: 5.0 },
      { month: "Mar", value: 5.2, target: 5.0 },
      { month: "Apr", value: 5.5, target: 5.0 },
      { month: "May", value: 6.0, target: 5.0 },
      { month: "Jun", value: 6.8, target: 5.0 },
    ],
    plantBreakdown: [
      { plant: "Sakri Solar Park", cluster: "Dhule", vendor: "SolarCo India", value: 8.2, status: "Non-Compliant" },
      { plant: "Sangli Solar Farm", cluster: "Sangli", vendor: "SunPower Tech", value: 7.5, status: "Warning" },
      { plant: "Osmanabad Solar Plant", cluster: "Osmanabad", vendor: "Green Energy Ltd", value: 5.8, status: "Warning" },
      { plant: "Amravati Solar Unit", cluster: "Amravati", vendor: "SolarCo India", value: 4.2, status: "Compliant" },
    ],
    waterfallData: [
      { step: "Expected Generation", value: 100.0, type: "total" },
      { step: "Equipment Downtime", value: -2.5, type: "decrease" },
      { step: "Soiling Loss", value: -1.2, type: "decrease" },
      { step: "Curtailment", value: -1.8, type: "decrease" },
      { step: "Grid Unavailability", value: -0.8, type: "decrease" },
      { step: "Other Losses", value: -0.5, type: "decrease" },
      { step: "Actual Generation", value: 93.2, type: "total" },
    ],
    versions: [
      {
        version: "v1.5",
        effectiveDate: "2024-05-01",
        snapshot: "LPI = Sum(All Operational Losses) / Expected Generation * 100",
        approvedBy: "Anil Kapoor",
        status: "Active",
        revenueImpactChange: 0,
        ldExposureChange: 0,
        complianceChange: 0,
      },
    ],
  },
  // Commercial
  {
    id: "rev-real",
    name: "Revenue Realization",
    category: "Commercial",
    currentValue: 42.85,
    targetValue: 45.0,
    unit: "₹ L",
    complianceStatus: "Warning",
    momChange: -4.8,
    trend: [43.2, 44.1, 45.5, 44.8, 43.9, 44.3, 42.85],
    description: "Total revenue generated based on billing.",
    ppaType: "PPA-Solar-2018",
    effectiveVersion: "v1.0",
    impactedPlants: 5,
    revenueImpact: -215000,
    ldRisk: 0,
    benchmarkSource: "Billing Schedule A",
    history: [
      { month: "Jan", value: 43.2, target: 45.0 },
      { month: "Feb", value: 44.1, target: 45.0 },
      { month: "Mar", value: 45.5, target: 45.0 },
      { month: "Apr", value: 44.8, target: 45.0 },
      { month: "May", value: 43.9, target: 45.0 },
      { month: "Jun", value: 42.85, target: 45.0 },
    ],
    plantBreakdown: [
      { plant: "Sakri Solar Park", cluster: "Dhule", vendor: "SolarCo India", value: 40.5, status: "Warning" },
      { plant: "Sangli Solar Farm", cluster: "Sangli", vendor: "SunPower Tech", value: 43.2, status: "Warning" },
      { plant: "Osmanabad Solar Plant", cluster: "Osmanabad", vendor: "Green Energy Ltd", value: 45.8, status: "Compliant" },
      { plant: "Latur Solar Station", cluster: "Latur", vendor: "TechSolar Pvt", value: 42.0, status: "Warning" },
    ],
    waterfallData: [
      { step: "Contracted Revenue", value: 45.0, type: "total" },
      { step: "Generation Shortfall", value: -1.5, type: "decrease" },
      { step: "Tariff Adjustment", value: -0.3, type: "decrease" },
      { step: "Payment Delay", value: -0.35, type: "decrease" },
      { step: "Actual Revenue", value: 42.85, type: "total" },
    ],
    versions: [
      {
        version: "v1.0",
        effectiveDate: "2024-01-01",
        snapshot: "Revenue = Units Billed * Tariff",
        approvedBy: "Meera Nair",
        status: "Active",
        revenueImpactChange: 0,
        ldExposureChange: 0,
        complianceChange: 0,
      },
    ],
  },
  {
    id: "rev-shortfall",
    name: "Revenue Shortfall",
    category: "Commercial",
    currentValue: 2.15,
    targetValue: 0.5,
    unit: "₹ L",
    complianceStatus: "Non-Compliant",
    momChange: 330.0,
    trend: [0.8, 1.2, 0.9, 1.5, 1.8, 2.0, 2.15],
    description: "Gap between contracted and realized revenue due to operational losses.",
    ppaType: "PPA-Solar-2018",
    effectiveVersion: "v1.1",
    impactedPlants: 8,
    revenueImpact: -2150000,
    ldRisk: 450000,
    benchmarkSource: "Commercial Terms, Clause 6.4",
    history: [
      { month: "Jan", value: 0.8, target: 0.5 },
      { month: "Feb", value: 1.2, target: 0.5 },
      { month: "Mar", value: 0.9, target: 0.5 },
      { month: "Apr", value: 1.5, target: 0.5 },
      { month: "May", value: 1.8, target: 0.5 },
      { month: "Jun", value: 2.15, target: 0.5 },
    ],
    plantBreakdown: [
      { plant: "Sakri Solar Park", cluster: "Dhule", vendor: "SolarCo India", value: 0.85, status: "Non-Compliant" },
      { plant: "Sangli Solar Farm", cluster: "Sangli", vendor: "SunPower Tech", value: 0.65, status: "Warning" },
      { plant: "Beed Solar Park", cluster: "Beed", vendor: "Mega Solar Inc", value: 0.45, status: "Warning" },
      { plant: "Devdaithan Solar Plant", cluster: "Ahmednagar", vendor: "Mega Solar Inc", value: 0.20, status: "Compliant" },
    ],
    waterfallData: [
      { step: "Contracted Revenue", value: 45.0, type: "total" },
      { step: "CUF Shortfall", value: -0.85, type: "decrease" },
      { step: "Availability Loss", value: -0.45, type: "decrease" },
      { step: "Curtailment Impact", value: -0.60, type: "decrease" },
      { step: "Other Factors", value: -0.25, type: "decrease" },
      { step: "Realized Revenue", value: 42.85, type: "total" },
    ],
    versions: [
      {
        version: "v1.1",
        effectiveDate: "2024-04-01",
        snapshot: "Shortfall = Contracted Revenue - Realized Revenue",
        approvedBy: "Sanjay Mehta",
        status: "Active",
        revenueImpactChange: 0,
        ldExposureChange: 0,
        complianceChange: 0,
      },
    ],
  },
  {
    id: "om-deviation",
    name: "O&M Deviation",
    category: "Commercial",
    currentValue: 8.5,
    targetValue: 5.0,
    unit: "%",
    complianceStatus: "Warning",
    momChange: 70.0,
    trend: [4.2, 5.0, 5.8, 6.5, 7.2, 7.8, 8.5],
    description: "Deviation of actual O&M costs from budgeted operational expenses.",
    ppaType: "Internal Budget-2024",
    effectiveVersion: "v1.0",
    impactedPlants: 10,
    revenueImpact: -425000,
    ldRisk: 0,
    benchmarkSource: "Annual Budget, Section 3",
    history: [
      { month: "Jan", value: 4.2, target: 5.0 },
      { month: "Feb", value: 5.0, target: 5.0 },
      { month: "Mar", value: 5.8, target: 5.0 },
      { month: "Apr", value: 6.5, target: 5.0 },
      { month: "May", value: 7.2, target: 5.0 },
      { month: "Jun", value: 8.5, target: 5.0 },
    ],
    plantBreakdown: [
      { plant: "Sakri Solar Park", cluster: "Dhule", vendor: "SolarCo India", value: 12.5, status: "Non-Compliant" },
      { plant: "Sangli Solar Farm", cluster: "Sangli", vendor: "SunPower Tech", value: 9.2, status: "Warning" },
      { plant: "Osmanabad Solar Plant", cluster: "Osmanabad", vendor: "Green Energy Ltd", value: 6.8, status: "Warning" },
      { plant: "Wardha Solar Park", cluster: "Ahmednagar", vendor: "Mega Solar Inc", value: 4.2, status: "Compliant" },
    ],
    waterfallData: [
      { step: "Budgeted O&M", value: 100.0, type: "total" },
      { step: "Unplanned Repairs", value: 3.5, type: "increase" },
      { step: "Spare Parts", value: 2.8, type: "increase" },
      { step: "Additional Labor", value: 1.5, type: "increase" },
      { step: "Emergency Response", value: 0.7, type: "increase" },
      { step: "Actual O&M", value: 108.5, type: "total" },
    ],
    versions: [
      {
        version: "v1.0",
        effectiveDate: "2024-01-01",
        snapshot: "O&M Deviation = ((Actual - Budget) / Budget) * 100",
        approvedBy: "Kavita Desai",
        status: "Active",
        revenueImpactChange: 0,
        ldExposureChange: 0,
        complianceChange: 0,
      },
    ],
  },
  {
    id: "ld",
    name: "Liquidated Damages (LD)",
    category: "Commercial",
    currentValue: 2.4,
    targetValue: 0.0,
    unit: "₹ L",
    complianceStatus: "Non-Compliant",
    momChange: 12.5,
    trend: [2.1, 2.2, 2.5, 2.3, 2.8, 2.6, 2.4],
    ldRisk: 240000,
    description: "Estimated penalty for non-performance.",
    ppaType: "PPA-Solar-2018",
    effectiveVersion: "v1.3",
    impactedPlants: 3,
    revenueImpact: -240000,
    benchmarkSource: "Penalty Clause 9.1",
    history: [
      { month: "Jan", value: 2.1, target: 0.0 },
      { month: "Feb", value: 2.2, target: 0.0 },
      { month: "Mar", value: 2.5, target: 0.0 },
      { month: "Apr", value: 2.3, target: 0.0 },
      { month: "May", value: 2.8, target: 0.0 },
      { month: "Jun", value: 2.4, target: 0.0 },
    ],
    plantBreakdown: [
      { plant: "Sakri Solar Park", cluster: "Dhule", vendor: "SolarCo India", value: 0.95, status: "Non-Compliant" },
      { plant: "Sangli Solar Farm", cluster: "Sangli", vendor: "SunPower Tech", value: 0.85, status: "Non-Compliant" },
      { plant: "Beed Solar Park", cluster: "Beed", vendor: "Mega Solar Inc", value: 0.60, status: "Non-Compliant" },
    ],
    waterfallData: [
      { step: "Base", value: 0.0, type: "total" },
      { step: "CUF Penalty", value: 1.25, type: "increase" },
      { step: "Availability Penalty", value: 0.65, type: "increase" },
      { step: "Quality Penalty", value: 0.35, type: "increase" },
      { step: "Waivers Applied", value: -0.20, type: "decrease" },
      { step: "Force Majeure Adj", value: 0.35, type: "increase" },
      { step: "Total LD", value: 2.4, type: "total" },
    ],
    versions: [
      {
        version: "v1.3",
        effectiveDate: "2024-02-01",
        snapshot: "LD = Sum(Penalty Components) - Waivers",
        approvedBy: "Ravi Shankar",
        status: "Active",
        revenueImpactChange: 0,
        ldExposureChange: 0,
        complianceChange: 0,
      },
    ],
  },
  {
    id: "roi",
    name: "ROI",
    category: "Commercial",
    currentValue: 11.2,
    targetValue: 12.0,
    unit: "%",
    complianceStatus: "Warning",
    momChange: -6.7,
    trend: [10.8, 11.0, 11.5, 11.8, 11.6, 11.4, 11.2],
    description: "Return on Investment for solar assets portfolio.",
    ppaType: "Internal Metrics",
    effectiveVersion: "v2.0",
    impactedPlants: 25,
    revenueImpact: -950000,
    ldRisk: 0,
    benchmarkSource: "Financial Policy, Section 2.1",
    history: [
      { month: "Jan", value: 10.8, target: 12.0 },
      { month: "Feb", value: 11.0, target: 12.0 },
      { month: "Mar", value: 11.5, target: 12.0 },
      { month: "Apr", value: 11.8, target: 12.0 },
      { month: "May", value: 11.6, target: 12.0 },
      { month: "Jun", value: 11.2, target: 12.0 },
    ],
    plantBreakdown: [
      { plant: "Sakri Solar Park", cluster: "Dhule", vendor: "SolarCo India", value: 9.8, status: "Warning" },
      { plant: "Osmanabad Solar Plant", cluster: "Osmanabad", vendor: "Green Energy Ltd", value: 12.5, status: "Compliant" },
      { plant: "Amravati Solar Unit", cluster: "Amravati", vendor: "SolarCo India", value: 11.8, status: "Warning" },
      { plant: "Latur Solar Station", cluster: "Latur", vendor: "TechSolar Pvt", value: 10.5, status: "Warning" },
    ],
    waterfallData: [
      { step: "Target ROI", value: 12.0, type: "total" },
      { step: "Revenue Impact", value: -0.45, type: "decrease" },
      { step: "O&M Overrun", value: -0.25, type: "decrease" },
      { step: "LD Impact", value: -0.10, type: "decrease" },
      { step: "Actual ROI", value: 11.2, type: "total" },
    ],
    versions: [
      {
        version: "v2.0",
        effectiveDate: "2024-01-01",
        snapshot: "ROI = (Net Profit / Investment) * 100",
        approvedBy: "CFO - Deepak Joshi",
        status: "Active",
        revenueImpactChange: 0,
        ldExposureChange: 0,
        complianceChange: 0,
      },
    ],
  },
  {
    id: "payback",
    name: "Payback Period",
    category: "Commercial",
    currentValue: 9.2,
    targetValue: 8.5,
    unit: "years",
    complianceStatus: "Warning",
    momChange: 8.2,
    trend: [8.5, 8.6, 8.7, 8.9, 9.0, 9.1, 9.2],
    description: "Estimated time to recover initial investment based on current performance.",
    ppaType: "Internal Metrics",
    effectiveVersion: "v1.0",
    impactedPlants: 25,
    revenueImpact: -1200000,
    ldRisk: 0,
    benchmarkSource: "Investment Policy, Annexure B",
    history: [
      { month: "Jan", value: 8.5, target: 8.5 },
      { month: "Feb", value: 8.6, target: 8.5 },
      { month: "Mar", value: 8.7, target: 8.5 },
      { month: "Apr", value: 8.9, target: 8.5 },
      { month: "May", value: 9.0, target: 8.5 },
      { month: "Jun", value: 9.2, target: 8.5 },
    ],
    plantBreakdown: [
      { plant: "Sakri Solar Park", cluster: "Dhule", vendor: "SolarCo India", value: 10.5, status: "Non-Compliant" },
      { plant: "Sangli Solar Farm", cluster: "Sangli", vendor: "SunPower Tech", value: 9.8, status: "Warning" },
      { plant: "Osmanabad Solar Plant", cluster: "Osmanabad", vendor: "Green Energy Ltd", value: 8.2, status: "Compliant" },
      { plant: "Beed Solar Park", cluster: "Beed", vendor: "Mega Solar Inc", value: 7.8, status: "Compliant" },
    ],
    waterfallData: [
      { step: "Base Case", value: 8.5, type: "total" },
      { step: "Revenue Shortfall", value: 0.35, type: "increase" },
      { step: "O&M Increase", value: 0.25, type: "increase" },
      { step: "LD Impact", value: 0.10, type: "increase" },
      { step: "Actual Payback", value: 9.2, type: "total" },
    ],
    versions: [
      {
        version: "v1.0",
        effectiveDate: "2024-01-01",
        snapshot: "Payback = Investment / Annual Net Cash Flow",
        approvedBy: "CFO - Deepak Joshi",
        status: "Active",
        revenueImpactChange: 0,
        ldExposureChange: 0,
        complianceChange: 0,
      },
    ],
  },
  // AI/Predictive
  {
    id: "pdr",
    name: "Degradation Ratio (PDR)",
    category: "AI/Predictive",
    currentValue: 0.65,
    targetValue: 0.70,
    unit: "%/yr",
    complianceStatus: "Compliant",
    momChange: -7.1,
    trend: [0.50, 0.58, 0.62, 0.65, 0.65, 0.65, 0.65],
    description: "Annual degradation rate of PV modules.",
    ppaType: "Warranty-2018",
    effectiveVersion: "v1.0",
    impactedPlants: 0,
    revenueImpact: 0,
    ldRisk: 0,
    benchmarkSource: "Manufacturer Warranty",
    history: [
      { month: "Jan", value: 0.62, target: 0.70 },
      { month: "Feb", value: 0.63, target: 0.70 },
      { month: "Mar", value: 0.64, target: 0.70 },
      { month: "Apr", value: 0.65, target: 0.70 },
      { month: "May", value: 0.65, target: 0.70 },
      { month: "Jun", value: 0.65, target: 0.70 },
    ],
    plantBreakdown: [
      { plant: "Sakri Solar Park", cluster: "Dhule", vendor: "SolarCo India", value: 0.72, status: "Warning" },
      { plant: "Sangli Solar Farm", cluster: "Sangli", vendor: "SunPower Tech", value: 0.68, status: "Compliant" },
      { plant: "Osmanabad Solar Plant", cluster: "Osmanabad", vendor: "Green Energy Ltd", value: 0.58, status: "Compliant" },
      { plant: "Chandrapur Solar Project", cluster: "Chandrapur", vendor: "SunPower Tech", value: 0.85, status: "Non-Compliant" },
    ],
    waterfallData: [
      { step: "Year 1 Output", value: 100.0, type: "total" },
      { step: "Year 2 Loss", value: -0.65, type: "decrease" },
      { step: "Year 3 Loss", value: -0.65, type: "decrease" },
      { step: "Year 4 Loss", value: -0.65, type: "decrease" },
      { step: "Projected Year 4", value: 98.05, type: "total" },
    ],
    aiInsight: {
      confidence: 85,
      predictedValue: 0.68,
      anomalyDetected: false,
      recommendation: "Module degradation is within expected limits. Monitor block 4 for slight deviation.",
    },
    versions: [
      {
        version: "v1.0",
        effectiveDate: "2023-01-01",
        snapshot: "PDR = (Year1_Output - CurrentYear_Output) / Years_Operational",
        approvedBy: "Dr. Ananya Sen",
        status: "Active",
        revenueImpactChange: 0,
        ldExposureChange: 0,
        complianceChange: 0,
      },
    ],
  },
  {
    id: "forecast",
    name: "Forecasted Generation",
    category: "AI/Predictive",
    currentValue: 4500,
    targetValue: 4400,
    unit: "MWh",
    complianceStatus: "Compliant",
    momChange: 2.3,
    trend: [4200, 4300, 4400, 4500, 4600, 4700],
    description: "AI-based generation forecast for next month.",
    ppaType: "N/A",
    effectiveVersion: "v2.1",
    impactedPlants: 0,
    revenueImpact: 0,
    ldRisk: 0,
    benchmarkSource: "AI Model v3",
    history: [
      { month: "Jan", value: 4200, target: 4200 },
      { month: "Feb", value: 4300, target: 4250 },
      { month: "Mar", value: 4400, target: 4300 },
      { month: "Apr", value: 4500, target: 4400 },
      { month: "May", value: 4600, target: 4500 },
      { month: "Jun", value: 4500, target: 4400 },
    ],
    plantBreakdown: [
      { plant: "Sakri Solar Park", cluster: "Dhule", vendor: "SolarCo India", value: 1200, status: "Compliant" },
      { plant: "Sangli Solar Farm", cluster: "Sangli", vendor: "SunPower Tech", value: 1100, status: "Compliant" },
      { plant: "Osmanabad Solar Plant", cluster: "Osmanabad", vendor: "Green Energy Ltd", value: 1300, status: "Compliant" },
      { plant: "Wardha Solar Park", cluster: "Wardha", vendor: "SunPower Tech", value: 900, status: "Compliant" },
    ],
    waterfallData: [
      { step: "Base Forecast", value: 4200, type: "total" },
      { step: "Weather Adj", value: 250, type: "increase" },
      { step: "Seasonal Factor", value: 150, type: "increase" },
      { step: "Maintenance Impact", value: -100, type: "decrease" },
      { step: "Final Forecast", value: 4500, type: "total" },
    ],
    aiInsight: {
      confidence: 92,
      predictedValue: 4650,
      anomalyDetected: true,
      recommendation: "Weather pattern suggests higher irradiance next month. Schedule maintenance accordingly.",
    },
    versions: [
      {
        version: "v2.1",
        effectiveDate: "2024-03-01",
        snapshot: "AI Model v3 with LSTM + Weather Integration",
        approvedBy: "Dr. Vikram AI Lead",
        status: "Active",
        revenueImpactChange: 0,
        ldExposureChange: 0,
        complianceChange: 0,
      },
    ],
  },
  {
    id: "curtailment-pattern",
    name: "Curtailment Pattern Analysis",
    category: "AI/Predictive",
    currentValue: 72,
    targetValue: 80,
    unit: "score",
    complianceStatus: "Warning",
    momChange: -10.0,
    trend: [75, 76, 78, 80, 78, 74, 72],
    description: "AI-driven predictive score for curtailment risk patterns based on grid behavior.",
    ppaType: "N/A",
    effectiveVersion: "v1.5",
    impactedPlants: 12,
    revenueImpact: -320000,
    ldRisk: 85000,
    benchmarkSource: "AI Analytics Model v2",
    history: [
      { month: "Jan", value: 75, target: 80 },
      { month: "Feb", value: 76, target: 80 },
      { month: "Mar", value: 78, target: 80 },
      { month: "Apr", value: 80, target: 80 },
      { month: "May", value: 78, target: 80 },
      { month: "Jun", value: 72, target: 80 },
    ],
    plantBreakdown: [
      { plant: "Sakri Solar Park", cluster: "Dhule", vendor: "SolarCo India", value: 65, status: "Warning" },
      { plant: "Sangli Solar Farm", cluster: "Sangli", vendor: "SunPower Tech", value: 68, status: "Warning" },
      { plant: "Beed Solar Park", cluster: "Beed", vendor: "Mega Solar Inc", value: 58, status: "Non-Compliant" },
      { plant: "Devdaithan Solar Plant", cluster: "Ahmednagar", vendor: "Mega Solar Inc", value: 82, status: "Compliant" },
    ],
    waterfallData: [
      { step: "Baseline Score", value: 100, type: "total" },
      { step: "Grid Congestion Risk", value: -12, type: "decrease" },
      { step: "Frequency Volatility", value: -8, type: "decrease" },
      { step: "Historical Pattern", value: -5, type: "decrease" },
      { step: "Seasonal Factor", value: -3, type: "decrease" },
      { step: "Current Score", value: 72, type: "total" },
    ],
    aiInsight: {
      confidence: 88,
      predictedValue: 68,
      anomalyDetected: true,
      recommendation: "High curtailment risk detected for northern region during peak hours. Consider energy storage integration or demand-side management.",
    },
    versions: [
      {
        version: "v1.5",
        effectiveDate: "2024-06-01",
        snapshot: "AI Pattern Recognition with Time-Series ARIMA + Grid Load Forecasting",
        approvedBy: "Dr. Priya Data Science",
        status: "Active",
        revenueImpactChange: 0,
        ldExposureChange: 0,
        complianceChange: 0,
      },
      {
        version: "v1.4",
        effectiveDate: "2024-01-01",
        snapshot: "AI Pattern Recognition with Time-Series Analysis",
        approvedBy: "Dr. Rajesh Analytics",
        status: "Archived",
        revenueImpactChange: -85000,
        ldExposureChange: 25000,
        complianceChange: -8.0,
      },
    ],
  },
];

export const versionHistory: KPIVersion[] = [
  {
    version: "v1.2",
    effectiveDate: "2024-01-01",
    snapshot: "CUF = (Gen / (Cap * Hours)) * 100",
    approvedBy: "John Doe",
    status: "Active",
    revenueImpactChange: 0,
    ldExposureChange: 0,
    complianceChange: 0,
  },
  {
    version: "v1.1",
    effectiveDate: "2023-06-01",
    snapshot: "CUF = (Gen / (Cap * Hours)) * 100",
    approvedBy: "Jane Smith",
    status: "Archived",
    revenueImpactChange: -50000,
    ldExposureChange: 10000,
    complianceChange: -2.5,
  },
];